language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install -e .[dev]
  - pip install -e .[optional]
# command to run tests
script:
  - python -m pytest
  - python setup.py check -ms
