language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  # PyPy versions
#  - "pypy3" # Pypy3 2.4.0
#  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install -e .[dev]
  - pip install -e .[optional]
# command to run tests
script:
  - python -m pytest
  - python setup.py check -ms
  - python setup.py build_sphinx -W
  - pylanguagetool --pwl spelling.txt --disabled-rules=WHITESPACE_RULE README.rst
